### PR TITLE
Update File Picker to use new Files API

### LINKED ISSUE #142: Fix file picker parsing error
I just noticed this bug, should be a quick fix but I think the problem lies in the HTTP 301 not being followed correctly:

image

image

### PR DESCRIPTION
**Pull request by msquee**
Closes #142

### CODE REVIEW

**Comment by johrstrom** [comment]
I wonder if just following the redirect works? that'd help with backward compatibility.

**Comment by msquee** [comment]
We can do that, but I think updating the API link is the better move because if we follow redirects then all HTTP requests will be N+1. We should move the File Picker into the Dashboard once we finalize the plan for the JS upgrades in the Dashboard.
**To follow redirects:**
```js
return fetch(pathmod.resolve(fs_api_root, path.replace(/(^\/)/, '')), {
  credentials: 'same-origin',
  redirect: 'follow',
});
```

**Comment by GloktarFR** [comment]
Hello,

I've been using the master branch of the js_filepicker with the master branch of ondemand.
But I'm still getting a parsing error very similar to this one.

Though, the nginx log shows a different message I think:

```
ERROR "No such file or directory @ rb_file_s_stat - /https:/ao-ood2/pun/sys/dashboard/files/fs/home/toto"
INFO "method=GET path=/pun/sys/dashboard/files/api/v1/fs/https:/ao-ood2/pun/sys/dashboard/files/fs/home/toto format=html controller=FilesController action=fs status=200 duration=49.26 view=28.12"
```

I've been trying to force the path using replacing the 'fetch' like this:
```
  return fetch('/pun/sys/files/api/v1/fs/home/toto', {
    credentials: 'same-origin',
    redirect: 'follow',
  });
```
Although I no longer see any error in the nginx log, I'm still getting the parsing error anyway.
```
INFO "method=GET path=/pun/sys/dashboard/files/api/v1/fs/home/toto format=html controller=FilesController action=fs status=200 duration=39.15 view=19.50"
```

**Comment by johrstrom** [comment]
Thanks! I opened another ticket - #150. I think @msquee may have identified this or similar. In any case thanks for the very good info in the comment!

**Pull request merged**
